apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}
  labels:
    {{- include "eclipse-mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |-
    {{- .Values.config | nindent 4 }}