apiVersion: v1
kind: Service
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}
  labels:
    {{- include "eclipse-mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: eclipse-mqtt
      protocol: TCP
      name: eclipse-mqtt
  selector:
    {{- include "eclipse-mosquitto.selectorLabels" . | nindent 4 }}
